- name: Install Debian dependencies
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  apt: name={{ item }}
  sudo: yes
  with_items:
    - nginx

- name: Install config
  template: src=nginx-config dest=/etc/nginx/sites-enabled/default owner=root group=root mode=0644

- name:  Reload haproxy
  service: name=nginx state=reloaded
