- name: Install Debian dependencies
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  apt: name={{ item }}
  sudo: yes
  with_items:
    - haproxy

- name: Install config
  template: src=haproxy.cfg dest=/etc/haproxy/haproxy.cfg owner=root group=root mode=0644

- name:  Reload haproxy
  service: name=haproxy state=reloaded
