- name: Install Debian dependencies
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  apt: name={{ item }}
  sudo: yes
  with_items:
    - tmux
    - git
    - vim
- name: Install SuSe dependencies
  when: ansible_distribution == 'openSUSE'
  zypper: name={{ item }}
  sudo: yes
  with_items:
    - tmux
    - git
    - vim
- name: Download vundle
  remote_user: greghaynes
  git: repo=https://github.com/gmarik/Vundle.vim.git dest=/home/greghaynes/.vim/bundle/Vundle.vim
- name: install vundle
  remote_user: greghaynes
  command: vim +PluginInstall +qall
- name: Make vim autoload dir
  remote_user: greghaynes
  file: path=/home/greghaynes/.vim/autoload state=directory mode=0755 owner=greghaynes
- name: Install Pathogen
  remote_user: greghaynes
  get_url: url=https://github.com/tpope/vim-pathogen/raw/master/autoload/pathogen.vim dest=/home/greghaynes/.vim/autoload/pathogen.vim mode=0644 owner=greghaynes
- name: Install vim solarized colors
  remote_user: greghaynes
  git: repo=https://github.com/altercation/vim-colors-solarized dest=/home/greghaynes/.vim/bundle/vim-colors-solarized.git
- name: Create projects dir
  file: path=/home/greghaynes/Projects state=directory mode=0755 owner=greghaynes
- name: Download github projects
  remote_user: greghaynes
  git: repo=https://github.com/greghaynes/{{ item }} dest=/home/greghaynes/Projects/greghaynes/{{ item }}
  with_items:
    - ansible-roles
- name: link dotfiles
  remote_user: greghaynes
  file: path=/home/greghaynes/{{ item }} src=/home/greghaynes/Projects/greghaynes/DotFiles/{{ item }} state=link mode=0644 owner=greghaynes
  with_items:
    - .vimrc
