- name: Install Debian dependencies
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  apt: name={{ item }}
  sudo: yes
  with_items:
    - tmux
    - git
- name: Install SuSe dependencies
  when: ansible_distribution == 'openSUSE'
  zypper: name={{ item }}
  sudo: yes
  with_items:
    - tmux
    - git
- name: Install RedHat dependencies
  when: ansible_distribution == 'CentOS'
  yum: name={{ item }}
  sudo: yes
  with_items:
    - tmux
    - git
- name: Create projects dir
  file: path=/home/greghaynes/Projects state=directory mode=0755 owner=greghaynes
- name: Download github projects
  remote_user: greghaynes
  git: repo=https://github.com/greghaynes/{{ item }} dest=/home/greghaynes/Projects/greghaynes/{{ item }}
  with_items:
    - ansible-roles
