- name: Check arguments
  fail: msg="{{ item }} is not defined"
  when: '{{ item }} is undefined'
  with_items:
    - arch
    - devnodes.cpus
    - engine
    - devnodes.memory
    - disk_path
  tags: [config-check]

- name: define vm
  virt: name={{ node_name }}
        command=define
        xml="{{ lookup('template', 'vm.xml') }}"
