- name: Install apt dependencies
  apt: name={{ item }}
  sudo: yes
  with_items:
    - zsh
    - tmux
    - git
    - vim
    - python-virtualenv
- name: Assert user
  user: name=greghaynes shell=/bin/zsh
  sudo: yes
- name: Download oh-my-zsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh dest=/home/greghaynes/.oh-my-zsh
- name: Download vundle
  git: repo=https://github.com/gmarik/Vundle.vim.git dest=/home/greghaynes/.vim/bundle/Vundle.vim
- name: install vundle
  command: vim +PluginInstall +qall
- name: Create projects dir
  file: path=/home/greghaynes/Projects state=directory mode=0755 owner=greghaynes
- name: Download github projects
  git: repo=git@github.com:greghaynes/{{ item }} dest=/home/greghaynes/Projects/{{ item }}
  with_items:
    - dib-dev-deploy
    - DotFiles
    - Mailase
- name: link dotfiles
  file: path=/home/greghaynes/{{ item }} src=/home/greghaynes/Projects/DotFiles/{{ item }} state=link mode=0644 owner=greghaynes
  with_items:
    - .gitconfig
    - .tmux.conf
    - .vimrc
    - .zshrc
