- name: Install Debian dependencies
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  apt: name={{ item }}
  sudo: yes
  with_items:
    - zsh
    - git-core
- name: Install SuSe dependencies
  when: ansible_distribution == 'openSUSE'
  zypper: name={{ item }}
  sudo: yes
  with_items:
    - zsh
    - git
- name: Install RedHat dependencies
  when: ansible_distribution == 'CentOS'
  yum: name={{ item }}
  sudo: yes
  with_items:
    - zsh
    - git
- name: Assert user
  user: name=greghaynes shell=/bin/zsh
  sudo: yes
- name: Assert ssh config dir
  file: path=/home/greghaynes/.ssh state=directory owner=greghaynes group=greghaynes mode=0700
- name: Copy ssh authorized_keys
  copy: src=authorized_keys dest=/home/greghaynes/.ssh/authorized_keys owner=greghaynes group=greghaynes mode=0600
  remote_user: greghaynes
- name: Download oh-my-zsh
  remote_user: greghaynes
  git: repo=https://github.com/robbyrussell/oh-my-zsh dest=/home/greghaynes/.oh-my-zsh
- name: Download DotFiles
  remote_user: greghaynes
  git: repo=https://github.com/greghaynes/{{ item }} dest=/home/greghaynes/Projects/greghaynes/{{ item }}
  with_items:
    - DotFiles
- name: link dotfiles
  remote_user: greghaynes
  file: path=/home/greghaynes/{{ item }} src=/home/greghaynes/Projects/greghaynes/DotFiles/{{ item }} state=link mode=0644 owner=greghaynes
  with_items:
    - .gitconfig
    - .tmux.conf
    - .zshrc
